import moo from 'moo'
export const lexer = moo.compile({
  __: /[ \t]+/u,
  //_: /[ \t]*/u,
  Year: /(?:\d{4}|n\.d\.?)/u,
  //maybename: /[A-Z]\w*['-]?\w*/u,
  Number: /0|[1-9]\d*/u,
  //Loc: ['pp.', 'p.', 'chapter', 'Chapter'],
  Com: ',',
  Dot: '.',
  Lp: '(',
  Rp: ')',
  Sem: ';',
  Col: ':',
  Amp: '&',
  And: 'and',
  Ca: ['ca.'],
  Quote: /["'](?:\\['"\\]|[^\n"'\\])*["']/u,
  Apo: /['’]/u,
  Slash: '/',
  Dash: /[—−–-]/u,
  Et: /et al\.?/u,
  Punct: /[?![\]{}<>]/u,
  Mc: ['Mc', 'Mac'],
  DutchPref: ['van', 'der', 'ter', 'ten', 'te', 'de'],
  Cap: /\p{Lu}/u,
  Lowword: /\p{Ll}+/u,
  NL: { match: /\n/u, lineBreaks: true },
  Misc: /./u,
})
