export type  Attributes = 
| AlignH
| AlignV
| RelFromH
| RelFromV
| WrapText
| CalendarType
| ConformanceClass
| VerticalAlignRun
| XAlign
| YAlign
| BreakBin
| BreakBinSub
| FType
| Jc
| LimLoc
| Script
| Shp
| Style
| TopBot
| AnimationBuildType
| AnimationChartOnlyBuildType
| AnimationDgmOnlyBuildType
| BevelPresetType
| BlackWhiteMode
| BlendMode
| BlipCompression
| ChartBuildStep
| ColorSchemeIndex
| CompoundLine
| DgmBuildStep
| EffectContainerType
| FontCollectionIndex
| LightRigDirection
| LightRigType
| LineCap
| LineEndLength
| LineEndType
| LineEndWidth
| OnOffStyleType
| PathFillMode
| PathShadeType
| PenAlignment
| PresetCameraType
| PresetColorVal
| PresetLineDashVal
| PresetMaterialType
| PresetPatternVal
| PresetShadowVal
| RectAlignment
| SchemeColorVal
| ShapeType
| SystemColorVal
| TextAlignType
| TextAnchoringType
| TextAutonumberScheme
| TextCapsType
| TextFontAlignType
| TextHorzOverflowType
| TextShapeType
| TextStrikeType
| TextTabAlignType
| TextUnderlineType
| TextVerticalType
| TextVertOverflowType
| TextWrappingType
| TileFlipMode
| AnnotationVMerge
| Border
| BrClear
| BrType
| CaptionPos
| ChapterSep
| CharacterSpacing
| CombineBrackets
| Direction
| DisplacedByCustomXml
| DocGrid
| DocPartBehavior
| DocPartGallery
| DocPartType
| DocProtect
| DropCap
| EdGrp
| EdnPos
| Em
| FFTextType
| FldCharType
| FontFamily
| FrameLayout
| FrameScrollbar
| FtnEdn
| FtnPos
| HAnchor
| HdrFtr
| HeightRule
| HexColorAuto
| HighlightColor
| Hint
| InfoTextType
| Jc
| JcTable
| LevelSuffix
| LineNumberRestart
| LineSpacingRule
| Lock
| MailMergeDest
| MailMergeDocType
| MailMergeOdsoFMDFieldType
| MailMergeSourceType
| Merge
| MultiLevelType
| NumberFormat
| ObjectDrawAspect
| ObjectUpdateMode
| PageBorderDisplay
| PageBorderOffset
| PageBorderZOrder
| PageOrientation
| Pitch
| Proof
| ProofErr
| PTabAlignment
| PTabLeader
| PTabRelativeTo
| RestartNumber
| RubyAlign
| SdtDateMappingType
| SectionMark
| Shd
| StyleSort
| StyleType
| TabJc
| TabTlc
| TargetScreenSz
| TblLayoutType
| TblOverlap
| TblStyleOverrideType
| TblWidth
| TextAlignment
| TextboxTightWrap
| TextDirection
| TextEffect
| Theme
| ThemeColor
| Underline
| VAnchor
| VerticalJc
| View
| WmlColorSchemeIndex
| Wrap
| Zoom
