import { italic } from './italic'
import { all } from '../all'
import { command } from './command'
import { root } from './root'
import { article } from './article'
import { body } from './body'
import { text } from './text'
import { front } from './front'
import { wrapChildren } from '../util/wrap-children'
import { environment } from './environment'
import { sub } from './sub'
import { sup } from './sup'
import { sec } from './sec'
import { listItem } from './listItem'
import { list } from './list'
import { tableWrap } from './tableWrap'
import { table } from './table'
import { tr } from './tr'
import { td } from './td'
import { refList } from './refList'
import { xref } from './xref'
import { fig } from './fig'
import { graphic } from './graphic'
import { extLink } from './extLink'
import { p } from './p'
export * from './italic'

export const handlers = {
  root,
  article,
  front,
  body,
  text,
  italic,
  command,
  xref,

  sub,
  sup,
  instruction: ignore,

  articleTitle: command,

  p,

  list,
  listItem,
  title: all,
  sec,

  label: command,
  caption: command,
  tableWrap,
  table,
  tr,
  td,
  fig,
  inlineGraphic: graphic,
  graphic,
  back: all,

  refList: refList,
  tbody: all,

  extLink,

  fnGroup: all,
  fn: all,

  xml: ignore,
  abbrevJournaltitle: ignore,
  abbrev: ignore,
  abstract: ignore,
  accessDate: ignore,
  ack: ignore,
  address: ignore,
  addrLine: ignore,
  affAlternatives: ignore,
  aff: ignore,
  alternatives: ignore,
  altText: ignore,
  altTitle: ignore,
  annotation: ignore,
  anonymous: ignore,
  answerSet: ignore,
  answer: ignore,
  appGroup: ignore,
  app: ignore,
  array: ignore,
  articleCategories: ignore,
  articleId: ignore,
  articleMeta: ignore,
  articleVersionalternatives: ignore,
  articleVersion: ignore,
  attrib: ignore,
  authorComment: ignore,
  authorNotes: ignore,
  awardDesc: ignore,
  awardGroup: ignore,
  awardId: ignore,
  awardName: ignore,
  bio: ignore,
  blockAlternatives: ignore,
  bold: command,
  boxedText: ignore,
  break: ignore,
  chapterTitle: ignore,
  chemStruct: ignore,
  chemStructwrap: ignore,
  citationAlternatives: ignore,
  city: ignore,
  code: ignore,
  colgroup: ignore,
  collabAlternatives: ignore,
  collab: ignore,
  col: ignore,
  comment: ignore,
  compoundKwdpart: ignore,
  compoundKwd: ignore,
  compoundSubjectpart: ignore,
  compoundSubject: ignore,
  confAcronym: ignore,
  confDate: ignore,
  conference: ignore,
  confLoc: ignore,
  confName: ignore,
  confNum: ignore,
  confSponsor: ignore,
  confTheme: ignore,
  contribGroup: wrapChildren,
  contribId: ignore,
  contrib: ignore,
  contributedResourcegroup: ignore,
  copyrightHolder: ignore,
  copyrightStatement: ignore,
  copyrightYear: ignore,
  corresp: ignore,
  country: ignore,
  counts: ignore,
  count: ignore,
  customMetagroup: ignore,
  customMeta: ignore,
  dataTitle: ignore,
  dateIncitation: ignore,
  date: ignore,
  day: ignore,
  defHead: ignore,
  defItem: ignore,
  defList: ignore,
  def: ignore,
  degrees: ignore,
  dispFormulagroup: ignore,
  dispFormula: ignore,
  dispQuote: ignore,
  edition: ignore,
  elementCitation: ignore,
  elocationId: ignore,
  email: ignore,
  equationCount: ignore,
  era: ignore,
  etal: ignore,
  eventDesc: ignore,
  event: ignore,
  explanation: ignore,
  extendedBy: ignore,
  fax: ignore,
  figCount: ignore,
  figGroup: ignore,
  fixedCase: ignore,
  floatsGroup: ignore,
  fpage: ignore,
  frontStub: ignore,
  fundingGroup: ignore,
  fundingSource: ignore,
  fundingStatement: ignore,
  givenNames: ignore,
  glossary: ignore,
  glyphData: ignore,
  glyphRef: ignore,
  gov: ignore,
  history: ignore,
  hr: ignore,
  indexTermrangeend: ignore,
  indexTerm: ignore,
  inlineFormula: ignore,
  inlineMedia: ignore,
  inlineSupplementarymaterial: ignore,
  institutionId: ignore,
  institution: ignore,
  institutionWrap: ignore,
  isbn: ignore,
  issnL: ignore,
  issn: ignore,
  issueId: ignore,
  issuePart: ignore,
  issueSponsor: ignore,
  issueSubtitle: ignore,
  issueTitlegroup: wrapChildren,
  issueTitle: ignore,
  issue: ignore,
  journalId: ignore,
  journalMeta: ignore,
  journalSubtitle: ignore,
  journalTitlegroup: wrapChildren,
  journalTitle: command,
  kwdGroup: ignore,
  kwd: ignore,
  licenseP: ignore,
  license: ignore,
  longDesc: ignore,
  lpage: ignore,
  media: ignore,
  metaName: ignore,
  metaValue: ignore,
  milestoneEnd: ignore,
  milestoneStart: ignore,
  mixedCitation: ignore,
  monospace: ignore,
  month: ignore,
  nameAlternatives: ignore,
  namedContent: ignore,
  name: ignore,
  nestedKwd: ignore,
  nlmCitation: ignore,
  notes: ignore,
  note: ignore,
  objectId: ignore,
  onBehalfof: ignore,
  openAccess: ignore,
  option: ignore,
  overlineEnd: ignore,
  overlineStart: ignore,
  overline: ignore,
  pageCount: ignore,
  pageRange: ignore,
  partTitle: ignore,
  patent: ignore,
  permissions: ignore,
  personGroup: ignore,
  phone: ignore,
  postalCode: ignore,
  prefix: ignore,
  preformat: ignore,
  price: ignore,
  principalAwardrecipient: ignore,
  principalInvestigator: ignore,
  privateChar: ignore,
  processingMeta: ignore,
  product: ignore,
  pubDatenotavailable: ignore,
  pubDate: ignore,
  pubHistory: ignore,
  pubId: ignore,
  publisherLoc: ignore,
  publisherName: ignore,
  publisher: ignore,
  questionPreamble: ignore,
  question: ignore,
  questionWrapgroup: ignore,
  questionWrap: ignore,
  rb: ignore,
  refCount: ignore,
  ref: ignore,
  relatedArticle: ignore,
  relatedObject: ignore,
  resourceId: ignore,
  resourceName: ignore,
  resourceWrap: ignore,
  response: ignore,
  restrictedBy: ignore,
  role: ignore,
  roman: ignore,
  rp: ignore,
  rt: ignore,
  ruby: ignore,
  sansSerif: command,
  sc: command,
  season: ignore,
  secMeta: ignore,
  seeAlso: ignore,
  see: ignore,
  selfUri: ignore,
  seriesText: ignore,
  seriesTitle: ignore,
  series: ignore,
  sigBlock: ignore,
  sig: ignore,
  size: ignore,
  source: ignore,
  speaker: ignore,
  speech: ignore,
  statement: ignore,
  state: ignore,
  stdOrganization: ignore,
  std: ignore,
  strike: ignore,
  stringConf: ignore,
  stringDate: ignore,
  stringName: ignore,
  styledContent: ignore,
  subArticle: ignore,
  subject: ignore,
  subjGroup: ignore,
  subtitle: ignore,
  suffix: ignore,
  supplementaryMaterial: ignore,
  supplement: ignore,
  supportDescription: ignore,
  supportGroup: ignore,
  supportSource: ignore,
  surname: ignore,
  tableCount: ignore,
  tableWrapfoot: ignore,
  tableWrapgroup: ignore,
  target: ignore,
  termHead: ignore,
  term: ignore,
  texMath: ignore,
  textualForm: ignore,
  tfoot: ignore,
  thead: ignore,
  th: ignore,
  timeStamp: ignore,
  titleGroup: wrapChildren,
  transAbstract: ignore,
  transSource: ignore,
  transSubtitle: ignore,
  transTitlegroup: wrapChildren,
  transTitle: command,
  underlineEnd: ignore,
  underlineStart: ignore,
  underline: ignore,
  unstructuredKwdgroup: ignore,
  uri: ignore,
  verseGroup: ignore,
  verseLine: ignore,
  version: ignore,
  volumeId: ignore,
  volumeIssuegroup: ignore,
  volumeSeries: command,
  volume: command,
  wordCount: ignore,
  x: ignore,
  year: ignore,
}

function ignore() {
  //
}
