import { italic } from './italic'
import { all } from '../all'
import { command } from './command'
import { root } from './root'
import { article } from './article'
import { body } from './body'
import { text } from './text'
import { front } from './front'
import { wrapChildren } from '../util/wrap-children'
import { environment } from './environment'
export * from './italic'

export const andlers = {
  root,
  article,
  front: 'preamble',
  body: 'document',
  text,
  //comment,
  doctype: ignore,
  title: command,
  applet: ignore,
  area: ignore,
  basefont: ignore,
  bgsound: ignore,
  caption: ignore,
  col: ignore,
  colgroup: ignore,
  //command: ignore,
  content: ignore,
  datalist: ignore,
  dialog: ignore,
  element: ignore,
  embed: ignore,
  frame: ignore,
  frameset: ignore,
  isindex: ignore,
  keygen: ignore,
  link: ignore,
  math: ignore,
  menu: ignore,
  menuitem: ignore,
  meta: ignore,
  nextid: ignore,
  noembed: ignore,
  noframes: ignore,
  optgroup: ignore,
  option: ignore,
  param: ignore,
  script: ignore,
  shadow: ignore,
  source: ignore,
  spacer: ignore,
  style: ignore,
  svg: ignore,
  template: ignore,
  track: ignore,

  abbr: all,
  acronym: all,
  bdi: all,
  bdo: all,
  big: all,
  blink: all,
  button: all,
  canvas: all,
  cite: all,
  data: all,
  details: all,
  dfn: all,
  font: all,
  ins: all,
  label: all,
  map: all,
  marquee: all,
  meter: all,
  nobr: all,
  noscript: all,
  object: all,
  output: all,
  progress: all,
  rb: all,
  rbc: all,
  rp: all,
  rt: all,
  rtc: all,
  ruby: all,
  slot: all,
  small: all,
  span: all,
  sup: all,
  sub: all,
  tbody: all,
  tfoot: all,
  thead: all,
  time: all,

  italic,

  // address: wrapChildren,
  // article: wrapChildren,
  // aside: wrapChildren,
  // body: wrapChildren,
  // center: wrapChildren,
  // div: wrapChildren,
  // fieldset: wrapChildren,
  // figcaption: wrapChildren,
  // figure: wrapChildren,
  // form: wrapChildren,
  // footer: wrapChildren,
  // header: wrapChildren,
  // hgroup: wrapChildren,
  // html: wrapChildren,
  // legend: wrapChildren,
  // main: wrapChildren,
  // multicol: wrapChildren,
  // nav: wrapChildren,
  // picture: wrapChildren,
  // section: wrapChildren,

  // a,
  // audio: media,
  // b: strong,
  // base,
  // blockquote,
  // br,
  // code: inlineCode,
  // dir: list,
  // dl,
  // dt: li,
  // dd: li,
  // del,
  // h1: heading,
  // h2: heading,
  // h3: heading,
  // h4: heading,
  // h5: heading,
  // h6: heading,
  // hr,
  // italic,
  // iframe,
  // img,
  // image: img,
  // input,
  // kbd: inlineCode,
  // li,
  // listing: code,
  // mark: em,
  // ol: list,
  // p,
  // plaintext: code,
  // pre: code,
  // q,
  // s: del,
  // samp: inlineCode,
  // select,
  // strike: del,
  // strong,
  // summary: p,
  // table,
  // td: tableCell,
  // textarea,
  // th: tableCell,
  // tr: tableRow,
  // tt: inlineCode,
  // u: em,
  // ul: list,
  // var: inlineCode,
  // video: media,
  // wbr,
  // xmp: code,
}

export const handlers = {
  root,
  article,
  front,
  body,
  text,
  italic,
  command,

  instruction: ignore,

  articleTitle: command,

  p: wrapChildren,

  list: environment,
  listItem: command,
  title: command,
  sec: wrapChildren,

  abbrevJournaltitle: ignore,
  abbrev: ignore,
  abstract: ignore,
  accessDate: ignore,
  ack: ignore,
  address: ignore,
  addrLine: ignore,
  affAlternatives: ignore,
  aff: ignore,
  alternatives: ignore,
  altText: ignore,
  altTitle: ignore,
  annotation: ignore,
  anonymous: ignore,
  answerSet: ignore,
  answer: ignore,
  appGroup: ignore,
  app: ignore,
  array: ignore,
  articleCategories: ignore,
  articleId: ignore,
  articleMeta: ignore,
  articleVersionalternatives: ignore,
  articleVersion: ignore,
  attrib: ignore,
  authorComment: ignore,
  authorNotes: ignore,
  awardDesc: ignore,
  awardGroup: ignore,
  awardId: ignore,
  awardName: ignore,
  back: ignore,
  bio: ignore,
  blockAlternatives: ignore,
  bold: command,
  boxedText: ignore,
  break: ignore,
  caption: ignore,
  chapterTitle: ignore,
  chemStruct: ignore,
  chemStructwrap: ignore,
  citationAlternatives: ignore,
  city: ignore,
  code: ignore,
  colgroup: ignore,
  collabAlternatives: ignore,
  collab: ignore,
  col: ignore,
  comment: ignore,
  compoundKwdpart: ignore,
  compoundKwd: ignore,
  compoundSubjectpart: ignore,
  compoundSubject: ignore,
  confAcronym: ignore,
  confDate: ignore,
  conference: ignore,
  confLoc: ignore,
  confName: ignore,
  confNum: ignore,
  confSponsor: ignore,
  confTheme: ignore,
  contribGroup: ignore,
  contribId: ignore,
  contrib: ignore,
  contributedResourcegroup: ignore,
  copyrightHolder: ignore,
  copyrightStatement: ignore,
  copyrightYear: ignore,
  corresp: ignore,
  country: ignore,
  counts: ignore,
  count: ignore,
  customMetagroup: ignore,
  customMeta: ignore,
  dataTitle: ignore,
  dateIncitation: ignore,
  date: ignore,
  day: ignore,
  defHead: ignore,
  defItem: ignore,
  defList: ignore,
  def: ignore,
  degrees: ignore,
  dispFormulagroup: ignore,
  dispFormula: ignore,
  dispQuote: ignore,
  edition: ignore,
  elementCitation: ignore,
  elocationId: ignore,
  email: ignore,
  equationCount: ignore,
  era: ignore,
  etal: ignore,
  eventDesc: ignore,
  event: ignore,
  explanation: ignore,
  extendedBy: ignore,
  extLink: ignore,
  fax: ignore,
  figCount: ignore,
  figGroup: ignore,
  fig: ignore,
  fixedCase: ignore,
  floatsGroup: ignore,
  fnGroup: ignore,
  fn: ignore,
  fpage: ignore,
  frontStub: ignore,
  fundingGroup: ignore,
  fundingSource: ignore,
  fundingStatement: ignore,
  givenNames: ignore,
  glossary: ignore,
  glyphData: ignore,
  glyphRef: ignore,
  gov: ignore,
  graphic: ignore,
  history: ignore,
  hr: ignore,
  indexTermrangeend: ignore,
  indexTerm: ignore,
  inlineFormula: ignore,
  inlineGraphic: ignore,
  inlineMedia: ignore,
  inlineSupplementarymaterial: ignore,
  institutionId: ignore,
  institution: ignore,
  institutionWrap: ignore,
  isbn: ignore,
  issnL: ignore,
  issn: ignore,
  issueId: ignore,
  issuePart: ignore,
  issueSponsor: ignore,
  issueSubtitle: ignore,
  issueTitlegroup: ignore,
  issueTitle: ignore,
  issue: ignore,
  journalId: ignore,
  journalMeta: ignore,
  journalSubtitle: ignore,
  journalTitlegroup: ignore,
  journalTitle: ignore,
  kwdGroup: ignore,
  kwd: ignore,
  label: ignore,
  licenseP: ignore,
  license: ignore,
  longDesc: ignore,
  lpage: ignore,
  media: ignore,
  metaName: ignore,
  metaValue: ignore,
  milestoneEnd: ignore,
  milestoneStart: ignore,
  mixedCitation: ignore,
  monospace: ignore,
  month: ignore,
  nameAlternatives: ignore,
  namedContent: ignore,
  name: ignore,
  nestedKwd: ignore,
  nlmCitation: ignore,
  notes: ignore,
  note: ignore,
  objectId: ignore,
  onBehalfof: ignore,
  openAccess: ignore,
  option: ignore,
  overlineEnd: ignore,
  overlineStart: ignore,
  overline: ignore,
  pageCount: ignore,
  pageRange: ignore,
  partTitle: ignore,
  patent: ignore,
  permissions: ignore,
  personGroup: ignore,
  phone: ignore,
  postalCode: ignore,
  prefix: ignore,
  preformat: ignore,
  price: ignore,
  principalAwardrecipient: ignore,
  principalInvestigator: ignore,
  privateChar: ignore,
  processingMeta: ignore,
  product: ignore,
  pubDatenotavailable: ignore,
  pubDate: ignore,
  pubHistory: ignore,
  pubId: ignore,
  publisherLoc: ignore,
  publisherName: ignore,
  publisher: ignore,
  questionPreamble: ignore,
  question: ignore,
  questionWrapgroup: ignore,
  questionWrap: ignore,
  rb: ignore,
  refCount: ignore,
  refList: ignore,
  ref: ignore,
  relatedArticle: ignore,
  relatedObject: ignore,
  resourceId: ignore,
  resourceName: ignore,
  resourceWrap: ignore,
  response: ignore,
  restrictedBy: ignore,
  role: ignore,
  roman: ignore,
  rp: ignore,
  rt: ignore,
  ruby: ignore,
  sansSerif: ignore,
  sc: command,
  season: ignore,
  secMeta: ignore,
  seeAlso: ignore,
  see: ignore,
  selfUri: ignore,
  seriesText: ignore,
  seriesTitle: ignore,
  series: ignore,
  sigBlock: ignore,
  sig: ignore,
  size: ignore,
  source: ignore,
  speaker: ignore,
  speech: ignore,
  statement: ignore,
  state: ignore,
  stdOrganization: ignore,
  std: ignore,
  strike: ignore,
  stringConf: ignore,
  stringDate: ignore,
  stringName: ignore,
  styledContent: ignore,
  subArticle: ignore,
  subject: ignore,
  subjGroup: ignore,
  subtitle: ignore,
  sub: ignore,
  suffix: ignore,
  supplementaryMaterial: ignore,
  supplement: ignore,
  supportDescription: ignore,
  supportGroup: ignore,
  supportSource: ignore,
  sup: ignore,
  surname: ignore,
  tableCount: ignore,
  table: ignore,
  tableWrapfoot: ignore,
  tableWrapgroup: ignore,
  tableWrap: ignore,
  target: ignore,
  tbody: ignore,
  td: ignore,
  termHead: ignore,
  term: ignore,
  texMath: ignore,
  textualForm: ignore,
  tfoot: ignore,
  thead: ignore,
  th: ignore,
  timeStamp: ignore,
  titleGroup: ignore,
  transAbstract: ignore,
  transSource: ignore,
  transSubtitle: ignore,
  transTitlegroup: ignore,
  transTitle: ignore,
  tr: ignore,
  underlineEnd: ignore,
  underlineStart: ignore,
  underline: ignore,
  unstructuredKwdgroup: ignore,
  uri: ignore,
  verseGroup: ignore,
  verseLine: ignore,
  version: ignore,
  volumeId: ignore,
  volumeIssuegroup: ignore,
  volumeSeries: ignore,
  volume: ignore,
  wordCount: ignore,
  xref: ignore,
  x: ignore,
  year: ignore,
}

function ignore() {}
