name: split
on:
  workflow_run:
    workflows: ['release']
    types:
      - completed
  workflow_dispatch:

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Split monorepo
        uses: tefkah/monorepo-split@main
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          org: TrialAndErrorOrg
          match: './libs/unified-latex/* ./libs/jast/* ./libs/reoff/* ./libs/ooxast/* ./libs/rejour/* ./libs/xast/* ./libs/notion/* ./libs/citations/*'
          package-json: true
          description: true
          name: true
          topics: true
          # force: true
