name: TODO to issue

on:
  push:
    branches: [main]

permissions:
  contents: read
  issues: write

jobs:
  todo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: TODO to issue
        uses: alstr/todo-to-issue-action@v5
